version: '2'
services:
  db:
    image: mysql:5.7
    container_name: "node_mysql"
    environment:
      - MYSQL_ROOT_PASSWORD="savvycom2018"
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=app
    ports:
      - 3307:3306
    volumes:
      - /home/ubuntu/nodejs/db:/var/lib/mysql
  app:
    build: .
    container_name: "node_backend"
    volumes:
      - /home/ubuntu/nodejs:/usr/src/nodeapp
    ports:
      - 8080:8080
      - 22
    links:
      - db
